### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/audio-analysis#140]
We intend for this project to be released as an open source project.
There are a few things we have to complete before this becomes a reality:

- [x] Basic approval
  - ✔️  Paul has said we can do this
- [x] Intellectual property
  - [x] Clear open sourcing with QUT Bluebox
  - [x] Check IP of any student code
  - [x] Choose an open source lisence
     - [x] Dual licence - code before open source commit should have a restricted licence
- [x] Code removal and cleanup
  - [x] Remove dev methods (See #134 )
  - [x] Do a full backup of the repository
  - [x] Fix as many warnings as possible
  - [x] Remove uneeded projects
    - [x] Dong.Felt
    - [x] QutBioacoustics.Xie
    - [x] AudioBrowser
    - [x] FSharp.FELT.*
  - [x] Remove old/dead code
   - [x] Clear Sandpit.cs
   - [x] Search for any remove any reference to absolute paths (e.g. `C:\..`)
  - [x] Remove most of the MATLAB code (keep stuff for AED, remove anything done by students)
  - [x] Remove all RCode
  - [x] Investigate reducing size of repo
    - [x] git-filter branch Extra-assemblies
  - [x] Reorganize folders (src, test etc...)
  - [x] Fix old dependencies
    - [x] Dynamic yaml (See #119)
    - [x] PowerArgs (See #145)
- [x] Other
  - [x] Add a scripts folder that has demos of common scripts
  - [x] Add/enhance our basic documentation - See #130
  - [x] Add a standard citation for the software (in README.md and printed in logs)
  - ~~[ ] Add analysis specific citations~~ See https://github.com/QutEcoacoustics/audio-analysis/issues/149
  - [x] Update GitHub issue template and contributing guide
  - ~~[ ] Add app metrics~~ https://github.com/QutEcoacoustics/audio-analysis/issues/150

**Comment by atruskie** [comment]
This was finally completed in 6ea3cbb3d74f34b6f5503378ea1301f1a9a66244
